// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sukalibur;

#nullable disable

namespace Sukalibur.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240824022045_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sukalibur.Graph.Organizers.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("organizers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9634),
                            Email = "root@sukalibur.com",
                            Name = "Root",
                            Phone = "14025",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9634),
                            Username = "root"
                        });
                });

            modelBuilder.Entity("Sukalibur.Graph.Trips.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("organizer_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9662),
                            Description = "Main Trip Description",
                            OrganizerId = 1,
                            Title = "Main Trip",
                            UpdatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9663)
                        });
                });

            modelBuilder.Entity("Sukalibur.Graph.Trips.TripCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.ToTable("trip_categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9581),
                            Description = "",
                            Name = "Open Trip",
                            UpdatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9582)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9585),
                            Description = "",
                            Name = "Private Trip",
                            UpdatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9585)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9586),
                            Description = "",
                            Name = "Group Trip",
                            UpdatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(9587)
                        });
                });

            modelBuilder.Entity("Sukalibur.Graph.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(8666),
                            Email = "root@sukalibur.com",
                            FullName = "Root",
                            Gender = 2,
                            Password = "",
                            Phone = "",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 8, 24, 2, 20, 45, 296, DateTimeKind.Utc).AddTicks(8667),
                            Username = "root"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 8, 1, 1, 9, 46, 930, DateTimeKind.Local).AddTicks(831),
                            Email = "Kathy_Cassin17@gmail.com",
                            FullName = "Kathy Cassin",
                            Gender = 0,
                            Password = "4B9dLkIPOn",
                            Phone = "1-550-485-3107",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 12, 28, 23, 21, 9, 856, DateTimeKind.Local).AddTicks(9302),
                            Username = "Kathy.Cassin"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 2, 1, 10, 25, 20, 740, DateTimeKind.Local).AddTicks(1579),
                            Email = "Pat37@yahoo.com",
                            FullName = "Pat Ward",
                            Gender = 0,
                            Password = "6wpS215xjs",
                            Phone = "457-908-9371 x143",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 2, 2, 19, 35, 28, 273, DateTimeKind.Local).AddTicks(5920),
                            Username = "Pat.Ward"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 8, 5, 5, 56, 50, 312, DateTimeKind.Local).AddTicks(401),
                            Email = "Katherine_Metz@yahoo.com",
                            FullName = "Katherine Metz",
                            Gender = 2,
                            Password = "OclAQd3RjW",
                            Phone = "1-219-274-5419",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 8, 4, 0, 13, 38, 674, DateTimeKind.Local).AddTicks(937),
                            Username = "Katherine_Metz"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 6, 13, 21, 26, 39, 628, DateTimeKind.Local).AddTicks(9066),
                            Email = "Jon.DAmore@hotmail.com",
                            FullName = "Jon D'Amore",
                            Gender = 1,
                            Password = "AWA1y12qAZ",
                            Phone = "819.456.3904",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 11, 9, 1, 22, 17, 571, DateTimeKind.Local).AddTicks(1390),
                            Username = "Jon27"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 11, 7, 8, 46, 56, 585, DateTimeKind.Local).AddTicks(6206),
                            Email = "Cassandra.Osinski31@hotmail.com",
                            FullName = "Cassandra Osinski",
                            Gender = 2,
                            Password = "XkSRjQdutA",
                            Phone = "895.580.4415 x409",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 10, 20, 3, 34, 31, 609, DateTimeKind.Local).AddTicks(6764),
                            Username = "Cassandra_Osinski"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 4, 12, 0, 41, 52, 58, DateTimeKind.Local).AddTicks(7103),
                            Email = "Rachael.Ondricka71@hotmail.com",
                            FullName = "Rachael Ondricka",
                            Gender = 0,
                            Password = "Kojt7sZKhK",
                            Phone = "1-383-459-9083 x83191",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 7, 4, 1, 6, 6, 528, DateTimeKind.Local).AddTicks(5940),
                            Username = "Rachael79"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 8, 28, 4, 47, 45, 116, DateTimeKind.Local).AddTicks(592),
                            Email = "Jonathan.Kunde62@yahoo.com",
                            FullName = "Jonathan Kunde",
                            Gender = 0,
                            Password = "tIqV_rqUur",
                            Phone = "1-445-411-9376",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 5, 7, 17, 26, 39, 545, DateTimeKind.Local).AddTicks(4631),
                            Username = "Jonathan.Kunde"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 2, 9, 20, 8, 12, 211, DateTimeKind.Local).AddTicks(8324),
                            Email = "Don_Block@gmail.com",
                            FullName = "Don Block",
                            Gender = 2,
                            Password = "8p0DGangFm",
                            Phone = "(645) 409-2519 x84826",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 6, 9, 13, 57, 22, 70, DateTimeKind.Local).AddTicks(667),
                            Username = "Don24"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 3, 10, 23, 10, 14, 447, DateTimeKind.Local).AddTicks(4681),
                            Email = "Kelli36@hotmail.com",
                            FullName = "Kelli McGlynn",
                            Gender = 0,
                            Password = "Hb7GcedScl",
                            Phone = "677-911-6569",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 4, 14, 18, 26, 4, 932, DateTimeKind.Local).AddTicks(4953),
                            Username = "Kelli74"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 4, 14, 7, 2, 4, 281, DateTimeKind.Local).AddTicks(5845),
                            Email = "Gustavo60@hotmail.com",
                            FullName = "Gustavo Bartoletti",
                            Gender = 2,
                            Password = "J2YGDCXpPD",
                            Phone = "(695) 910-7777 x29275",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 7, 29, 22, 44, 36, 801, DateTimeKind.Local).AddTicks(7437),
                            Username = "Gustavo41"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 1, 1, 13, 16, 29, 204, DateTimeKind.Local).AddTicks(2362),
                            Email = "Vincent_Herman53@gmail.com",
                            FullName = "Vincent Herman",
                            Gender = 1,
                            Password = "nTkqeFppW5",
                            Phone = "(461) 304-8475",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 8, 20, 20, 57, 18, 704, DateTimeKind.Local).AddTicks(8106),
                            Username = "Vincent70"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 8, 17, 7, 8, 15, 517, DateTimeKind.Local).AddTicks(5069),
                            Email = "Kent47@hotmail.com",
                            FullName = "Kent Blick",
                            Gender = 0,
                            Password = "UswhRhuf_j",
                            Phone = "420-858-2501",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 3, 10, 20, 6, 11, 11, DateTimeKind.Local).AddTicks(7742),
                            Username = "Kent_Blick"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 11, 28, 17, 7, 6, 953, DateTimeKind.Local).AddTicks(8559),
                            Email = "Randy84@gmail.com",
                            FullName = "Randy Wilderman",
                            Gender = 1,
                            Password = "tsi70Tuvrg",
                            Phone = "655.288.7674 x92333",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 1, 11, 2, 12, 4, 347, DateTimeKind.Local).AddTicks(5115),
                            Username = "Randy_Wilderman61"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 7, 9, 0, 13, 18, 341, DateTimeKind.Local).AddTicks(6216),
                            Email = "Carolyn83@hotmail.com",
                            FullName = "Carolyn Koepp",
                            Gender = 1,
                            Password = "lTrT3sJGY3",
                            Phone = "(875) 872-2686 x225",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 5, 17, 8, 38, 38, 39, DateTimeKind.Local).AddTicks(7841),
                            Username = "Carolyn64"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 10, 12, 14, 25, 27, 350, DateTimeKind.Local).AddTicks(6514),
                            Email = "Sara69@yahoo.com",
                            FullName = "Sara Stanton",
                            Gender = 1,
                            Password = "0LoIxe35dl",
                            Phone = "(229) 911-7287",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 5, 13, 15, 14, 20, 902, DateTimeKind.Local).AddTicks(2335),
                            Username = "Sara.Stanton57"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 4, 14, 9, 26, 16, 251, DateTimeKind.Local).AddTicks(5599),
                            Email = "Melinda83@gmail.com",
                            FullName = "Melinda Wisozk",
                            Gender = 0,
                            Password = "E8o2ahVW3o",
                            Phone = "(715) 442-9793",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 9, 4, 0, 3, 18, 468, DateTimeKind.Local).AddTicks(3523),
                            Username = "Melinda_Wisozk"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 5, 19, 9, 41, 45, 949, DateTimeKind.Local).AddTicks(2701),
                            Email = "Viola82@yahoo.com",
                            FullName = "Viola O'Conner",
                            Gender = 2,
                            Password = "taeTRzLkl7",
                            Phone = "1-218-650-0027",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 10, 30, 3, 47, 14, 816, DateTimeKind.Local).AddTicks(2763),
                            Username = "Viola21"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 5, 3, 9, 12, 6, 239, DateTimeKind.Local).AddTicks(4690),
                            Email = "Vera_Wiza@hotmail.com",
                            FullName = "Vera Wiza",
                            Gender = 2,
                            Password = "FED4OY4U8R",
                            Phone = "(341) 544-9285 x66662",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 11, 10, 12, 1, 3, 865, DateTimeKind.Local).AddTicks(1555),
                            Username = "Vera.Wiza"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 1, 28, 9, 10, 1, 798, DateTimeKind.Local).AddTicks(9831),
                            Email = "Kevin92@gmail.com",
                            FullName = "Kevin Schiller",
                            Gender = 0,
                            Password = "gwxOGg0pNw",
                            Phone = "(611) 709-2828",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 9, 5, 13, 33, 41, 63, DateTimeKind.Local).AddTicks(3778),
                            Username = "Kevin.Schiller"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 8, 7, 8, 54, 50, 398, DateTimeKind.Local).AddTicks(1300),
                            Email = "Ruth_Durgan27@yahoo.com",
                            FullName = "Ruth Durgan",
                            Gender = 1,
                            Password = "7Hqkn5Wpn_",
                            Phone = "332-611-2017 x233",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 8, 29, 7, 46, 4, 663, DateTimeKind.Local).AddTicks(4362),
                            Username = "Ruth.Durgan"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 7, 21, 13, 59, 0, 559, DateTimeKind.Local).AddTicks(7104),
                            Email = "Terrell88@yahoo.com",
                            FullName = "Terrell Bosco",
                            Gender = 0,
                            Password = "jHpNHhK7Up",
                            Phone = "315-410-3279",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 2, 10, 4, 14, 17, 521, DateTimeKind.Local).AddTicks(191),
                            Username = "Terrell_Bosco"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 2, 21, 2, 40, 6, 290, DateTimeKind.Local).AddTicks(2803),
                            Email = "Blanca.Rohan55@hotmail.com",
                            FullName = "Blanca Rohan",
                            Gender = 2,
                            Password = "ksKKTYLdhn",
                            Phone = "662.823.5771 x2313",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 3, 17, 9, 16, 50, 614, DateTimeKind.Local).AddTicks(7270),
                            Username = "Blanca.Rohan"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 10, 14, 4, 40, 14, 155, DateTimeKind.Local).AddTicks(6342),
                            Email = "Carroll.Baumbach15@hotmail.com",
                            FullName = "Carroll Baumbach",
                            Gender = 1,
                            Password = "twl9lKUsVh",
                            Phone = "(915) 624-1624",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 2, 15, 21, 32, 22, 648, DateTimeKind.Local).AddTicks(3167),
                            Username = "Carroll0"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 12, 9, 20, 56, 43, 349, DateTimeKind.Local).AddTicks(5615),
                            Email = "Allan.Beahan@hotmail.com",
                            FullName = "Allan Beahan",
                            Gender = 0,
                            Password = "Q8pfgrAZH2",
                            Phone = "1-289-428-9051 x67983",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 2, 24, 2, 9, 37, 125, DateTimeKind.Local).AddTicks(4319),
                            Username = "Allan.Beahan75"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 8, 5, 12, 57, 20, 116, DateTimeKind.Local).AddTicks(7366),
                            Email = "Blanca_Runte2@hotmail.com",
                            FullName = "Blanca Runte",
                            Gender = 1,
                            Password = "vKC6hUtKXg",
                            Phone = "419-702-4120",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 7, 24, 4, 41, 56, 187, DateTimeKind.Local).AddTicks(6651),
                            Username = "Blanca_Runte21"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 11, 4, 7, 7, 12, 848, DateTimeKind.Local).AddTicks(552),
                            Email = "Kate_Bashirian76@hotmail.com",
                            FullName = "Kate Bashirian",
                            Gender = 2,
                            Password = "rH4XZPkdah",
                            Phone = "832-951-3889 x6450",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 6, 17, 1, 19, 33, 761, DateTimeKind.Local).AddTicks(7505),
                            Username = "Kate_Bashirian"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 7, 5, 0, 40, 16, 474, DateTimeKind.Local).AddTicks(7360),
                            Email = "Brent27@yahoo.com",
                            FullName = "Brent Kassulke",
                            Gender = 2,
                            Password = "ycwe5vEeoL",
                            Phone = "310.679.9716 x4094",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 11, 16, 20, 51, 9, 484, DateTimeKind.Local).AddTicks(8412),
                            Username = "Brent78"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 11, 12, 7, 36, 0, 935, DateTimeKind.Local).AddTicks(1825),
                            Email = "Alex_Cole71@gmail.com",
                            FullName = "Alex Cole",
                            Gender = 2,
                            Password = "_9gDrP93n3",
                            Phone = "697-306-4676 x8115",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 2, 10, 15, 56, 55, 177, DateTimeKind.Local).AddTicks(4924),
                            Username = "Alex.Cole99"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 8, 31, 19, 7, 24, 863, DateTimeKind.Local).AddTicks(8784),
                            Email = "Susie31@gmail.com",
                            FullName = "Susie Hoeger",
                            Gender = 0,
                            Password = "NGt7aVIRn6",
                            Phone = "(993) 717-4405",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 8, 28, 1, 7, 16, 606, DateTimeKind.Local).AddTicks(1993),
                            Username = "Susie.Hoeger98"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 10, 16, 0, 41, 43, 548, DateTimeKind.Local).AddTicks(5762),
                            Email = "Dale.Murazik84@hotmail.com",
                            FullName = "Dale Murazik",
                            Gender = 0,
                            Password = "T1wbzhHzpL",
                            Phone = "1-577-968-5813 x862",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 12, 21, 9, 41, 50, 217, DateTimeKind.Local).AddTicks(9585),
                            Username = "Dale_Murazik"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 1, 10, 8, 4, 50, 471, DateTimeKind.Local).AddTicks(6496),
                            Email = "Zachary.Ward@gmail.com",
                            FullName = "Zachary Ward",
                            Gender = 0,
                            Password = "Pn2q3u56c5",
                            Phone = "442-646-3404 x2822",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 7, 16, 4, 9, 27, 30, DateTimeKind.Local).AddTicks(2458),
                            Username = "Zachary_Ward"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 10, 4, 2, 55, 59, 729, DateTimeKind.Local).AddTicks(8670),
                            Email = "Maria92@hotmail.com",
                            FullName = "Maria Schumm",
                            Gender = 1,
                            Password = "E2zY3rS9LA",
                            Phone = "1-862-230-0653 x70506",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 12, 11, 23, 50, 53, 469, DateTimeKind.Local).AddTicks(1623),
                            Username = "Maria33"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 12, 20, 6, 23, 43, 177, DateTimeKind.Local).AddTicks(9394),
                            Email = "Adrienne15@hotmail.com",
                            FullName = "Adrienne King",
                            Gender = 0,
                            Password = "wlQRZzOwkM",
                            Phone = "(467) 514-3178 x79430",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 5, 15, 3, 12, 8, 825, DateTimeKind.Local).AddTicks(9177),
                            Username = "Adrienne88"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 9, 20, 13, 39, 0, 120, DateTimeKind.Local).AddTicks(8227),
                            Email = "Edwin.Wilkinson98@hotmail.com",
                            FullName = "Edwin Wilkinson",
                            Gender = 1,
                            Password = "DN6yP1b8K_",
                            Phone = "319.638.6408 x1161",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 2, 16, 12, 33, 33, 6, DateTimeKind.Local).AddTicks(8582),
                            Username = "Edwin.Wilkinson"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 11, 9, 18, 15, 29, 793, DateTimeKind.Local).AddTicks(8389),
                            Email = "Cody_Cronin@yahoo.com",
                            FullName = "Cody Cronin",
                            Gender = 1,
                            Password = "KQGPVCVj64",
                            Phone = "1-412-685-5327 x0677",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 10, 18, 7, 25, 14, 88, DateTimeKind.Local).AddTicks(6475),
                            Username = "Cody.Cronin51"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 11, 3, 4, 55, 41, 879, DateTimeKind.Local).AddTicks(9378),
                            Email = "Donnie_Murray@hotmail.com",
                            FullName = "Donnie Murray",
                            Gender = 2,
                            Password = "viTkuXFfVG",
                            Phone = "1-928-747-7305",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 9, 26, 10, 20, 31, 999, DateTimeKind.Local).AddTicks(7805),
                            Username = "Donnie66"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 9, 26, 4, 12, 21, 578, DateTimeKind.Local).AddTicks(9673),
                            Email = "Natalie27@yahoo.com",
                            FullName = "Natalie Fadel",
                            Gender = 2,
                            Password = "Wy6_Aqztoq",
                            Phone = "816.356.6349",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 11, 3, 3, 38, 31, 441, DateTimeKind.Local).AddTicks(9202),
                            Username = "Natalie_Fadel"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 9, 21, 14, 32, 37, 433, DateTimeKind.Local).AddTicks(6904),
                            Email = "Casey_Harvey@hotmail.com",
                            FullName = "Casey Harvey",
                            Gender = 0,
                            Password = "xGcRyZoBSm",
                            Phone = "953-429-5319 x31279",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 8, 7, 17, 14, 44, 920, DateTimeKind.Local).AddTicks(7041),
                            Username = "Casey52"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 12, 25, 20, 46, 36, 203, DateTimeKind.Local).AddTicks(6412),
                            Email = "Carroll_Carter@yahoo.com",
                            FullName = "Carroll Carter",
                            Gender = 0,
                            Password = "m7scOxQzyy",
                            Phone = "538.440.0338 x079",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 5, 6, 8, 49, 25, 151, DateTimeKind.Local).AddTicks(461),
                            Username = "Carroll_Carter75"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 5, 12, 21, 1, 49, 725, DateTimeKind.Local).AddTicks(8631),
                            Email = "Felipe.Hegmann@gmail.com",
                            FullName = "Felipe Hegmann",
                            Gender = 2,
                            Password = "_jDjPvU5yz",
                            Phone = "766-357-5046",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 1, 20, 20, 55, 1, 943, DateTimeKind.Local).AddTicks(3644),
                            Username = "Felipe14"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 6, 27, 16, 33, 27, 31, DateTimeKind.Local).AddTicks(2557),
                            Email = "Ricky.Farrell@gmail.com",
                            FullName = "Ricky Farrell",
                            Gender = 1,
                            Password = "jsv0aLDpsM",
                            Phone = "323.846.0196 x581",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 12, 30, 1, 45, 44, 218, DateTimeKind.Local).AddTicks(8647),
                            Username = "Ricky.Farrell"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2024, 5, 3, 21, 3, 47, 557, DateTimeKind.Local).AddTicks(853),
                            Email = "Antoinette_Batz18@yahoo.com",
                            FullName = "Antoinette Batz",
                            Gender = 0,
                            Password = "FgjLHDoWut",
                            Phone = "1-539-427-2467",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 5, 8, 27, 596, DateTimeKind.Local).AddTicks(9541),
                            Username = "Antoinette69"
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2024, 2, 26, 9, 54, 53, 487, DateTimeKind.Local).AddTicks(4066),
                            Email = "Jennifer_Pfeffer62@gmail.com",
                            FullName = "Jennifer Pfeffer",
                            Gender = 1,
                            Password = "ZEC5mnUCXm",
                            Phone = "1-298-813-1171 x28362",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 4, 24, 21, 58, 13, 118, DateTimeKind.Local).AddTicks(3707),
                            Username = "Jennifer_Pfeffer99"
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2024, 7, 13, 18, 24, 5, 481, DateTimeKind.Local).AddTicks(1663),
                            Email = "Lloyd34@gmail.com",
                            FullName = "Lloyd Ullrich",
                            Gender = 0,
                            Password = "aCw8JWsMP5",
                            Phone = "1-683-380-4965 x0545",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 1, 26, 10, 0, 13, 136, DateTimeKind.Local).AddTicks(3038),
                            Username = "Lloyd.Ullrich82"
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2024, 5, 30, 21, 16, 16, 564, DateTimeKind.Local).AddTicks(5036),
                            Email = "Sherman_Kshlerin@yahoo.com",
                            FullName = "Sherman Kshlerin",
                            Gender = 1,
                            Password = "wPu4lGDKtF",
                            Phone = "982-980-2147 x53819",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 10, 19, 20, 10, 30, 993, DateTimeKind.Local).AddTicks(9504),
                            Username = "Sherman_Kshlerin20"
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2024, 4, 5, 9, 14, 11, 488, DateTimeKind.Local).AddTicks(3497),
                            Email = "Yolanda.Harber40@hotmail.com",
                            FullName = "Yolanda Harber",
                            Gender = 0,
                            Password = "MFkdvziyFU",
                            Phone = "479.693.2796",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 1, 17, 13, 21, 34, 353, DateTimeKind.Local).AddTicks(6951),
                            Username = "Yolanda_Harber19"
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2024, 8, 16, 19, 47, 32, 941, DateTimeKind.Local).AddTicks(2314),
                            Email = "Jenny40@gmail.com",
                            FullName = "Jenny Kuhlman",
                            Gender = 2,
                            Password = "u3FJxGxb8L",
                            Phone = "563-626-6294",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 8, 29, 8, 17, 52, 480, DateTimeKind.Local).AddTicks(2877),
                            Username = "Jenny_Kuhlman"
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2024, 3, 17, 7, 35, 52, 456, DateTimeKind.Local).AddTicks(2995),
                            Email = "Sam.Connelly@yahoo.com",
                            FullName = "Sam Connelly",
                            Gender = 0,
                            Password = "LamtbNH3hM",
                            Phone = "518-345-2905",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 7, 28, 6, 1, 17, 542, DateTimeKind.Local).AddTicks(1985),
                            Username = "Sam60"
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2024, 3, 30, 18, 12, 50, 975, DateTimeKind.Local).AddTicks(4704),
                            Email = "Robert.Homenick15@gmail.com",
                            FullName = "Robert Homenick",
                            Gender = 0,
                            Password = "2gf46OgJOy",
                            Phone = "862-964-4237 x69405",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 8, 22, 11, 19, 45, 61, DateTimeKind.Local).AddTicks(5797),
                            Username = "Robert80"
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2023, 11, 4, 2, 11, 16, 329, DateTimeKind.Local).AddTicks(5397),
                            Email = "Maryann56@yahoo.com",
                            FullName = "Maryann Kemmer",
                            Gender = 1,
                            Password = "02fVzNKEnU",
                            Phone = "282-498-7113",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 12, 27, 10, 51, 14, 764, DateTimeKind.Local).AddTicks(5980),
                            Username = "Maryann_Kemmer"
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2024, 3, 5, 20, 12, 42, 272, DateTimeKind.Local).AddTicks(8873),
                            Email = "Rebecca8@hotmail.com",
                            FullName = "Rebecca Runte",
                            Gender = 2,
                            Password = "v_g_v8Fhlg",
                            Phone = "(824) 561-3878",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 9, 27, 20, 39, 56, 980, DateTimeKind.Local).AddTicks(9001),
                            Username = "Rebecca_Runte91"
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2024, 4, 23, 8, 6, 44, 73, DateTimeKind.Local).AddTicks(166),
                            Email = "Christy.Wehner@gmail.com",
                            FullName = "Christy Wehner",
                            Gender = 2,
                            Password = "wBDI7bFZYt",
                            Phone = "(803) 505-0193 x514",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 2, 19, 0, 57, 22, 291, DateTimeKind.Local).AddTicks(3548),
                            Username = "Christy14"
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2024, 4, 25, 20, 57, 4, 382, DateTimeKind.Local).AddTicks(9227),
                            Email = "Elisa.DuBuque@hotmail.com",
                            FullName = "Elisa DuBuque",
                            Gender = 2,
                            Password = "MPPiJEL8pR",
                            Phone = "823.798.0737 x77010",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 8, 4, 14, 12, 38, 920, DateTimeKind.Local).AddTicks(6048),
                            Username = "Elisa80"
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2024, 3, 21, 22, 48, 30, 595, DateTimeKind.Local).AddTicks(3794),
                            Email = "Dale_Prohaska39@hotmail.com",
                            FullName = "Dale Prohaska",
                            Gender = 1,
                            Password = "mLyuMFA2qa",
                            Phone = "607-462-1425",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 9, 13, 5, 34, 35, 840, DateTimeKind.Local).AddTicks(3810),
                            Username = "Dale49"
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2024, 2, 22, 1, 31, 59, 387, DateTimeKind.Local).AddTicks(8855),
                            Email = "Bill70@yahoo.com",
                            FullName = "Bill Klein",
                            Gender = 0,
                            Password = "Ay9cS7MqFB",
                            Phone = "667.885.8690 x0324",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 11, 6, 11, 18, 23, 291, DateTimeKind.Local).AddTicks(9338),
                            Username = "Bill_Klein"
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2023, 9, 2, 8, 56, 49, 985, DateTimeKind.Local).AddTicks(2690),
                            Email = "Luther.Fahey@gmail.com",
                            FullName = "Luther Fahey",
                            Gender = 1,
                            Password = "jqcyU9_4S9",
                            Phone = "1-480-438-1713",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 8, 11, 17, 2, 1, 390, DateTimeKind.Local).AddTicks(6084),
                            Username = "Luther_Fahey70"
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2024, 6, 6, 4, 43, 36, 406, DateTimeKind.Local).AddTicks(3934),
                            Email = "Misty_Lockman@hotmail.com",
                            FullName = "Misty Lockman",
                            Gender = 2,
                            Password = "Wy24_rGDei",
                            Phone = "(582) 230-2275 x6840",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 9, 10, 23, 9, 37, 888, DateTimeKind.Local).AddTicks(1187),
                            Username = "Misty39"
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2024, 3, 3, 2, 56, 43, 622, DateTimeKind.Local).AddTicks(9051),
                            Email = "Neal87@gmail.com",
                            FullName = "Neal Klein",
                            Gender = 1,
                            Password = "62WUrs2Zxp",
                            Phone = "1-813-201-0094 x64638",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 6, 28, 11, 14, 19, 415, DateTimeKind.Local).AddTicks(2352),
                            Username = "Neal_Klein19"
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2023, 10, 7, 13, 1, 30, 768, DateTimeKind.Local).AddTicks(3302),
                            Email = "Taylor.Barton@hotmail.com",
                            FullName = "Taylor Barton",
                            Gender = 0,
                            Password = "0fDIt8GVJO",
                            Phone = "389-268-7831 x566",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 11, 17, 8, 50, 26, 758, DateTimeKind.Local).AddTicks(3403),
                            Username = "Taylor.Barton"
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2023, 12, 27, 14, 31, 35, 503, DateTimeKind.Local).AddTicks(5336),
                            Email = "Abel_Herman88@gmail.com",
                            FullName = "Abel Herman",
                            Gender = 0,
                            Password = "iEKOsbFO8F",
                            Phone = "525-718-4633",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 6, 2, 21, 30, 24, 554, DateTimeKind.Local).AddTicks(1287),
                            Username = "Abel.Herman14"
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2024, 8, 24, 8, 23, 25, 367, DateTimeKind.Local).AddTicks(651),
                            Email = "Jeffrey_Treutel@yahoo.com",
                            FullName = "Jeffrey Treutel",
                            Gender = 0,
                            Password = "vFA5A9PrRe",
                            Phone = "345-454-6578",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 1, 5, 16, 37, 31, 246, DateTimeKind.Local).AddTicks(9952),
                            Username = "Jeffrey53"
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2023, 10, 10, 8, 23, 49, 222, DateTimeKind.Local).AddTicks(9813),
                            Email = "Leigh.Stamm85@gmail.com",
                            FullName = "Leigh Stamm",
                            Gender = 0,
                            Password = "Et_OP2GKmU",
                            Phone = "361-880-6266 x9698",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 12, 7, 18, 45, 41, 550, DateTimeKind.Local).AddTicks(8143),
                            Username = "Leigh.Stamm"
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2023, 12, 29, 15, 47, 34, 710, DateTimeKind.Local).AddTicks(9616),
                            Email = "Willie.Abshire@hotmail.com",
                            FullName = "Willie Abshire",
                            Gender = 0,
                            Password = "uZAP19xBTB",
                            Phone = "763.772.3369 x079",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 10, 4, 2, 33, 47, 430, DateTimeKind.Local).AddTicks(1865),
                            Username = "Willie24"
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2023, 11, 17, 9, 47, 41, 161, DateTimeKind.Local).AddTicks(8133),
                            Email = "Dustin.Schmitt0@gmail.com",
                            FullName = "Dustin Schmitt",
                            Gender = 2,
                            Password = "TluHl42rxE",
                            Phone = "1-577-296-1444",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 8, 21, 23, 58, 57, 255, DateTimeKind.Local).AddTicks(2674),
                            Username = "Dustin_Schmitt41"
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2023, 10, 6, 0, 15, 35, 402, DateTimeKind.Local).AddTicks(4225),
                            Email = "Garrett88@gmail.com",
                            FullName = "Garrett Kautzer",
                            Gender = 2,
                            Password = "xbCX9pFsY6",
                            Phone = "(287) 332-4006 x25102",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 1, 23, 3, 30, 40, 141, DateTimeKind.Local).AddTicks(5570),
                            Username = "Garrett25"
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2023, 10, 28, 9, 23, 10, 133, DateTimeKind.Local).AddTicks(7869),
                            Email = "Randolph.Senger@gmail.com",
                            FullName = "Randolph Senger",
                            Gender = 2,
                            Password = "CuctiNtwgu",
                            Phone = "1-690-246-8003 x302",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 7, 29, 15, 8, 4, 150, DateTimeKind.Local).AddTicks(7414),
                            Username = "Randolph.Senger"
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2024, 6, 13, 2, 12, 50, 836, DateTimeKind.Local).AddTicks(1196),
                            Email = "Robyn70@hotmail.com",
                            FullName = "Robyn Koch",
                            Gender = 2,
                            Password = "0H8aA_ed_h",
                            Phone = "483.652.9986 x901",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 10, 24, 3, 19, 49, 178, DateTimeKind.Local).AddTicks(766),
                            Username = "Robyn98"
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2023, 9, 9, 18, 12, 19, 372, DateTimeKind.Local).AddTicks(3799),
                            Email = "Lucille.Baumbach@hotmail.com",
                            FullName = "Lucille Baumbach",
                            Gender = 0,
                            Password = "9kV2cqOvRM",
                            Phone = "(489) 659-7034",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 1, 20, 2, 35, 14, 676, DateTimeKind.Local).AddTicks(6767),
                            Username = "Lucille59"
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2024, 1, 13, 18, 42, 27, 864, DateTimeKind.Local).AddTicks(797),
                            Email = "Alison_Schroeder@yahoo.com",
                            FullName = "Alison Schroeder",
                            Gender = 1,
                            Password = "xAC0Q2Koj3",
                            Phone = "684.432.8696 x420",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 10, 19, 0, 19, 14, 168, DateTimeKind.Local).AddTicks(8533),
                            Username = "Alison_Schroeder"
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2023, 12, 31, 8, 55, 10, 134, DateTimeKind.Local).AddTicks(2971),
                            Email = "Wesley.Ferry31@yahoo.com",
                            FullName = "Wesley Ferry",
                            Gender = 2,
                            Password = "S2WI8tkxC0",
                            Phone = "808.403.2264",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 5, 19, 12, 53, 22, 239, DateTimeKind.Local).AddTicks(9259),
                            Username = "Wesley.Ferry"
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2023, 12, 28, 1, 15, 4, 32, DateTimeKind.Local).AddTicks(4760),
                            Email = "Jon_Spinka@hotmail.com",
                            FullName = "Jon Spinka",
                            Gender = 0,
                            Password = "jmGrbwkAgb",
                            Phone = "1-744-445-4560",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 5, 7, 18, 58, 23, 689, DateTimeKind.Local).AddTicks(3911),
                            Username = "Jon.Spinka43"
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2023, 10, 5, 8, 34, 42, 664, DateTimeKind.Local).AddTicks(9036),
                            Email = "Steven19@gmail.com",
                            FullName = "Steven Leannon",
                            Gender = 0,
                            Password = "9UyaIf2xoW",
                            Phone = "288.960.7707 x1972",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 5, 16, 13, 7, 34, 939, DateTimeKind.Local).AddTicks(3349),
                            Username = "Steven50"
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2024, 4, 14, 15, 21, 59, 486, DateTimeKind.Local).AddTicks(9900),
                            Email = "Nettie.White3@hotmail.com",
                            FullName = "Nettie White",
                            Gender = 2,
                            Password = "5KX9CxBMw1",
                            Phone = "792-321-0535",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 5, 20, 11, 53, 40, 530, DateTimeKind.Local).AddTicks(2780),
                            Username = "Nettie.White42"
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2024, 6, 17, 6, 32, 18, 267, DateTimeKind.Local).AddTicks(1617),
                            Email = "Marsha53@hotmail.com",
                            FullName = "Marsha Lubowitz",
                            Gender = 1,
                            Password = "T7obodXcDG",
                            Phone = "909-363-1483 x7577",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 10, 23, 16, 13, 13, 643, DateTimeKind.Local).AddTicks(2794),
                            Username = "Marsha82"
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2023, 11, 5, 14, 31, 19, 914, DateTimeKind.Local).AddTicks(7776),
                            Email = "Robin_Okuneva@yahoo.com",
                            FullName = "Robin Okuneva",
                            Gender = 0,
                            Password = "aWv45La4Vs",
                            Phone = "430-374-8840",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 12, 2, 17, 7, 38, 52, DateTimeKind.Local).AddTicks(868),
                            Username = "Robin_Okuneva21"
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2024, 3, 18, 22, 32, 5, 2, DateTimeKind.Local).AddTicks(660),
                            Email = "Grant.Gleichner@yahoo.com",
                            FullName = "Grant Gleichner",
                            Gender = 2,
                            Password = "YoB1DI_yGo",
                            Phone = "(988) 870-9777 x639",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 9, 7, 20, 15, 22, 436, DateTimeKind.Local).AddTicks(3349),
                            Username = "Grant.Gleichner"
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2023, 11, 24, 17, 55, 58, 901, DateTimeKind.Local).AddTicks(6135),
                            Email = "Courtney.Kreiger@hotmail.com",
                            FullName = "Courtney Kreiger",
                            Gender = 0,
                            Password = "Dr_MaxnxTR",
                            Phone = "1-242-462-1423",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 10, 31, 3, 55, 54, 942, DateTimeKind.Local).AddTicks(336),
                            Username = "Courtney.Kreiger79"
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2024, 4, 13, 12, 38, 21, 355, DateTimeKind.Local).AddTicks(7319),
                            Email = "Virgil_Gorczany73@yahoo.com",
                            FullName = "Virgil Gorczany",
                            Gender = 0,
                            Password = "xrzIjpvTTH",
                            Phone = "(814) 486-0904",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 2, 5, 15, 33, 7, 641, DateTimeKind.Local).AddTicks(41),
                            Username = "Virgil_Gorczany10"
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2024, 4, 18, 21, 14, 47, 652, DateTimeKind.Local).AddTicks(511),
                            Email = "Arturo.Macejkovic@yahoo.com",
                            FullName = "Arturo Macejkovic",
                            Gender = 0,
                            Password = "2LTlSVy_lP",
                            Phone = "805.440.7508",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 10, 15, 3, 6, 21, 317, DateTimeKind.Local).AddTicks(5322),
                            Username = "Arturo.Macejkovic"
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2024, 7, 12, 7, 50, 22, 490, DateTimeKind.Local).AddTicks(8459),
                            Email = "Kristina95@gmail.com",
                            FullName = "Kristina Olson",
                            Gender = 2,
                            Password = "JZML032l8h",
                            Phone = "(688) 705-7172 x01437",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 8, 31, 10, 56, 52, 341, DateTimeKind.Local).AddTicks(9660),
                            Username = "Kristina79"
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2024, 1, 31, 5, 16, 52, 731, DateTimeKind.Local).AddTicks(1874),
                            Email = "Mark.Bartoletti@yahoo.com",
                            FullName = "Mark Bartoletti",
                            Gender = 1,
                            Password = "oMFEhhllIl",
                            Phone = "348.823.5001 x5518",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 12, 5, 19, 59, 59, 886, DateTimeKind.Local).AddTicks(2943),
                            Username = "Mark.Bartoletti78"
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2024, 6, 7, 14, 42, 24, 976, DateTimeKind.Local).AddTicks(6384),
                            Email = "Brad_Doyle2@hotmail.com",
                            FullName = "Brad Doyle",
                            Gender = 2,
                            Password = "nQMpni5gFN",
                            Phone = "1-771-262-6563",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 3, 23, 8, 59, 24, 889, DateTimeKind.Local).AddTicks(216),
                            Username = "Brad_Doyle"
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2024, 3, 31, 22, 25, 39, 765, DateTimeKind.Local).AddTicks(3786),
                            Email = "Heidi.Walter@hotmail.com",
                            FullName = "Heidi Walter",
                            Gender = 2,
                            Password = "8MGUl3xn1T",
                            Phone = "1-957-946-8302 x98502",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 12, 18, 1, 50, 24, 681, DateTimeKind.Local).AddTicks(1290),
                            Username = "Heidi79"
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2024, 8, 5, 3, 51, 18, 876, DateTimeKind.Local).AddTicks(7281),
                            Email = "William_Schamberger@hotmail.com",
                            FullName = "William Schamberger",
                            Gender = 1,
                            Password = "AlMAQplOKm",
                            Phone = "(277) 460-7025 x54405",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 12, 6, 12, 33, 42, 516, DateTimeKind.Local).AddTicks(8730),
                            Username = "William_Schamberger31"
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2023, 10, 10, 0, 54, 56, 322, DateTimeKind.Local).AddTicks(537),
                            Email = "Jodi.Hettinger@yahoo.com",
                            FullName = "Jodi Hettinger",
                            Gender = 0,
                            Password = "XTATlpvvaK",
                            Phone = "1-753-858-1139 x64032",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 1, 25, 17, 48, 16, 574, DateTimeKind.Local).AddTicks(1138),
                            Username = "Jodi.Hettinger"
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2024, 8, 14, 3, 17, 25, 575, DateTimeKind.Local).AddTicks(3863),
                            Email = "Laverne_Borer51@hotmail.com",
                            FullName = "Laverne Borer",
                            Gender = 2,
                            Password = "GnswLef8Lw",
                            Phone = "827.621.1595 x506",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 5, 41, 56, 50, DateTimeKind.Local).AddTicks(9935),
                            Username = "Laverne_Borer"
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2023, 10, 7, 6, 6, 2, 912, DateTimeKind.Local).AddTicks(7919),
                            Email = "Tyrone.Runolfsson55@gmail.com",
                            FullName = "Tyrone Runolfsson",
                            Gender = 1,
                            Password = "7gs6_NbInA",
                            Phone = "513.244.9359",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 12, 27, 21, 55, 10, 299, DateTimeKind.Local).AddTicks(4075),
                            Username = "Tyrone21"
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2023, 9, 1, 18, 39, 22, 183, DateTimeKind.Local).AddTicks(5207),
                            Email = "Pearl.Sauer40@gmail.com",
                            FullName = "Pearl Sauer",
                            Gender = 2,
                            Password = "BnPn7ah5Hk",
                            Phone = "398-674-7745 x97800",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 8, 31, 16, 14, 26, 607, DateTimeKind.Local).AddTicks(5488),
                            Username = "Pearl_Sauer"
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2023, 12, 12, 17, 53, 41, 915, DateTimeKind.Local).AddTicks(6277),
                            Email = "Taylor_Sawayn82@gmail.com",
                            FullName = "Taylor Sawayn",
                            Gender = 2,
                            Password = "Vez3Qg90MQ",
                            Phone = "544.899.2931 x00079",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 11, 27, 15, 35, 36, 178, DateTimeKind.Local).AddTicks(1894),
                            Username = "Taylor_Sawayn70"
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2023, 11, 21, 23, 58, 25, 958, DateTimeKind.Local).AddTicks(7389),
                            Email = "Lucia_Cummings70@hotmail.com",
                            FullName = "Lucia Cummings",
                            Gender = 1,
                            Password = "V2lAhKua6a",
                            Phone = "782-731-1634 x87814",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 6, 18, 7, 15, 58, 719, DateTimeKind.Local).AddTicks(9568),
                            Username = "Lucia.Cummings"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2024, 8, 12, 8, 52, 10, 367, DateTimeKind.Local).AddTicks(9441),
                            Email = "Israel_Carter58@hotmail.com",
                            FullName = "Israel Carter",
                            Gender = 2,
                            Password = "B9UDFHKS3f",
                            Phone = "1-710-688-9474",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 10, 16, 4, 15, 59, 753, DateTimeKind.Local).AddTicks(6933),
                            Username = "Israel80"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2024, 8, 19, 20, 43, 9, 500, DateTimeKind.Local).AddTicks(3298),
                            Email = "Rachael57@yahoo.com",
                            FullName = "Rachael Kovacek",
                            Gender = 1,
                            Password = "aRskDmlVoP",
                            Phone = "1-595-293-2772",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 5, 28, 10, 12, 1, 901, DateTimeKind.Local).AddTicks(9271),
                            Username = "Rachael96"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2023, 10, 23, 1, 46, 25, 55, DateTimeKind.Local).AddTicks(4386),
                            Email = "Joanne.Koss@gmail.com",
                            FullName = "Joanne Koss",
                            Gender = 0,
                            Password = "7UJgTKUdlW",
                            Phone = "967.797.4198 x7070",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 2, 24, 3, 53, 9, 528, DateTimeKind.Local).AddTicks(9416),
                            Username = "Joanne.Koss21"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2024, 1, 11, 19, 20, 15, 528, DateTimeKind.Local).AddTicks(2347),
                            Email = "Kent77@yahoo.com",
                            FullName = "Kent Morissette",
                            Gender = 1,
                            Password = "wDa3uFy2gq",
                            Phone = "1-957-405-3144 x5949",
                            Role = 1,
                            UpdatedAt = new DateTime(2024, 7, 24, 9, 4, 22, 975, DateTimeKind.Local).AddTicks(6033),
                            Username = "Kent_Morissette"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2024, 2, 7, 11, 6, 3, 875, DateTimeKind.Local).AddTicks(8897),
                            Email = "Tanya_Koch@yahoo.com",
                            FullName = "Tanya Koch",
                            Gender = 1,
                            Password = "Md0Wfdh0cD",
                            Phone = "977.421.1339",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 12, 2, 17, 2, 57, 110, DateTimeKind.Local).AddTicks(1865),
                            Username = "Tanya.Koch48"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2023, 12, 10, 12, 50, 5, 410, DateTimeKind.Local).AddTicks(181),
                            Email = "Heather87@gmail.com",
                            FullName = "Heather Block",
                            Gender = 1,
                            Password = "prY7dOgOvm",
                            Phone = "(745) 324-4344 x35953",
                            Role = 2,
                            UpdatedAt = new DateTime(2024, 6, 13, 21, 26, 17, 331, DateTimeKind.Local).AddTicks(5995),
                            Username = "Heather58"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2023, 11, 24, 14, 27, 13, 201, DateTimeKind.Local).AddTicks(9899),
                            Email = "Lindsey.Kuhic@hotmail.com",
                            FullName = "Lindsey Kuhic",
                            Gender = 2,
                            Password = "mDAolLDswR",
                            Phone = "1-266-675-6394",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 1, 55, 42, 246, DateTimeKind.Local).AddTicks(1432),
                            Username = "Lindsey.Kuhic83"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2023, 11, 28, 11, 51, 9, 622, DateTimeKind.Local).AddTicks(749),
                            Email = "Kim_Pfannerstill@hotmail.com",
                            FullName = "Kim Pfannerstill",
                            Gender = 2,
                            Password = "XGGgyVlJLy",
                            Phone = "1-450-998-1623",
                            Role = 1,
                            UpdatedAt = new DateTime(2023, 10, 23, 7, 55, 4, 161, DateTimeKind.Local).AddTicks(9088),
                            Username = "Kim_Pfannerstill"
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2024, 3, 18, 17, 33, 35, 561, DateTimeKind.Local).AddTicks(1076),
                            Email = "Marvin_Okuneva@yahoo.com",
                            FullName = "Marvin Okuneva",
                            Gender = 0,
                            Password = "XC4NxhNQld",
                            Phone = "1-992-588-8934 x160",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 2, 20, 9, 39, 17, 375, DateTimeKind.Local).AddTicks(2005),
                            Username = "Marvin.Okuneva"
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2023, 11, 19, 2, 22, 35, 587, DateTimeKind.Local).AddTicks(5573),
                            Email = "Carla77@gmail.com",
                            FullName = "Carla Wilkinson",
                            Gender = 2,
                            Password = "y2DcjxaC6p",
                            Phone = "(915) 780-2854 x7713",
                            Role = 0,
                            UpdatedAt = new DateTime(2023, 11, 14, 4, 16, 59, 994, DateTimeKind.Local).AddTicks(7060),
                            Username = "Carla.Wilkinson"
                        });
                });

            modelBuilder.Entity("Sukalibur.Graph.Trips.Trip", b =>
                {
                    b.HasOne("Sukalibur.Graph.Trips.TripCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Sukalibur.Graph.Organizers.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Organizer");
                });
#pragma warning restore 612, 618
        }
    }
}
